name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - id: major
        uses: ./
        with:
          version: v1.0.0
          type: major
      - id: minor
        uses: ./
        with:
          version: v1.0.0
          type: minor
      - id: patch
        uses: ./
        with:
          version: v1.0.0
          type: patch
      - name: Test major
        run: |
          [ "${{ steps.major.outputs.next_version }}" = "v2.0.0" ]
      - name: Test minor
        run: |
          [ "${{ steps.minor.outputs.next_version }}" = "v1.1.0" ]
      - name: Test patch
        run: |
          [ "${{ steps.patch.outputs.next_version }}" = "v1.0.1" ]
